import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";
import ClientLayout from "../components/ClientLayout";
import "./globals.css";
import "./storage-polyfill";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ViewTransitions>
          <ClientLayout>{children}</ClientLayout>
        </ViewTransitions>
      </body>
    </html>
  );
}
